### ISSUE TITLE
Cloning should use SSH

### ISSUE THREAD

**Issue by felipesabino** [indigotech/tqt-install#1]
As TQT is currently private, I suggest we use SSH instead of HTTPS.

HTTPS currently does not work directly if you have 2FA enable: 

https://help.github.com/articles/https-cloning-errors/#provide-access-token-if-2fa-enabled

> Provide access token if 2FA enabled
> 
> If you have enabled two-factor authentication, you must provide a personal access token instead of entering your password for HTTPS Git.

**Comment by mmassaki** [comment]
@felipesabino
I have 2FA enabled in my account and it works normally.

Github now [recommends using HTTPS instead of SSH](https://help.github.com/articles/set-up-git/#next-steps-authenticating-with-github-from-git) and you can use a personal access token as password as the quote you've posted.

It's working for me because I've cached my password (personal access token) in the keychain. [Github has a simple tutorial on how to do that](https://help.github.com/articles/caching-your-github-password-in-git/).

Also, I don't have SSH keys in my account anymore! I'm definitely not using SSH connections in Github and you should do the same for security sake. :wink:
